version: 2.1

workflow:
  version: 2
  build:
    jobs:
      - build:
          filters:
              branches:
                only:
                  - main
jobs:
  build:
    working_directory: ~/testDev
    docker: 
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
          name: install npm
          command: 'sudp npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json"}} 
          paths:
            - ./node_modules